### ISSUE TITLE
raspberry ralink MT7601U driver

### ISSUE THREAD

**Issue by vinnitu** [OpenELEC/wlan-firmware#7]
Here I found guige to inject driver into image of system

https://gist.github.com/basilfx/1485bfbaccec04bf7c4a

But maybe it can be done by official way?

**Comment by chewitt** [comment]
I will leave this PR open: https://github.com/OpenELEC/OpenELEC.tv/pull/3494 so people can download the build-system package I created and add it to their own image. I'm closing this ticket because the MT7601U driver doesn't use firmware.
